Seems like there is a theorem:

$$ A^n = PD^nP^{-1}$$

How is this proved? [MathExchange](https://math.stackexchange.com/questions/732511/fractional-power-of-matrix)



#### Diagonalization

We first need to calculate the eigenvectors and eigenvalues of the matrix.

Then Matrix D is equal to the a diagonal matrix that has all the eigenvalues as the main diagonal.

The matrix P is equal to a matrix with the eigenvectors as the columns.




In [27]:
import numpy as np

m = np.array([[-3, -4], [5, 6]])

values, eigenvector = np.linalg.eig(m)

print(values)
print(eigenvector)
print('---')
print(eigenvector[:, 1] * values[1])
print(np.matmul(m, eigenvector[:, 1]))
print('---')
# print(np.diag(1 / values))
q = np.matmul(eigenvector, np.diag(values ** (-1/2)))
print(np.matmul(q, np.linalg.inv(eigenvector)))

[1. 2.]
[[-0.70710678  0.62469505]
 [ 0.70710678 -0.78086881]]
---
[ 1.2493901  -1.56173762]
[ 1.2493901  -1.56173762]
---
[[ 2.17157288  1.17157288]
 [-1.46446609 -0.46446609]]


In [28]:
from scipy.linalg import fractional_matrix_power
import numpy as np

m = np.array([[-3, -4], [5, 6]])

calculated_frac = fractional_matrix_power(m, -1/2)

print(calculated_frac)




[[ 2.17157288  1.17157288]
 [-1.46446609 -0.46446609]]
